### ISSUE TITLE
[request] jupyterhub

### ISSUE THREAD

**Issue by danpolanco** [nazar-pc/docker-webserver-apps#1]
https://hub.docker.com/r/jupyter/jupyterhub/

Would it be possible to add this to the available apps? If it helps, I could try to figure it out and add a pull request.

**Comment by nazar-pc** [comment]
It seems to be Python-based app, isn't it?
This repository is intended to be complementary to https://github.com/nazar-pc/docker-webserver, which is in fact primarily designed for PHP.
In order to add Python-based app here we'll need to add Python support to https://github.com/nazar-pc/docker-webserver first. While I'm not developing anything in Python I can't do it properly.
So if it has nothing to do with https://github.com/nazar-pc/docker-webserver - there is no place for it here, otherwise I'm open for suggestions.

**Comment by danpolanco** [comment]
Makes sense. I'm not familiar enough with the project to comment on how it might be designed for PHP. Thanks!
